// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhjbvmyfzmjrfoodphuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoamJ2bXlmem1qcmZvb2RwaHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTk4MTcsImV4cCI6MjA2NzEzNTgxN30.7xIhkpvb0IgdjpHMhhdRV02tPd1LdrCZxsnn6uy5yy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});